name: Make Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Make Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Run Guard
        run: "node .guard"