name: Make Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Make Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install NPM Packages
        run: "cd .guard && npm i && cd .."
      - name: Run Guard
        run: "node .guard"
      - name: Save
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          user_name: "JacobLinCool"
          user_email: "jacoblincool@users.noreply.github.com"
          publish_branch: "homework"