name: Make Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Make Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install NPM Packages
        run: "cd .guard && npm i && cd .."
      - name: Cache Fonts
        uses: actions/cache@v2
        env:
          cache-name: cache-fonts
        with:
          path: /usr/share/fonts
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Fonts
        run: |
          sudo apt-get install language-pack-zh-hant
          wget -c https://noto-website.storage.googleapis.com/pkgs/Noto-hinted.zip
          unzip Noto-hinted.zip -d Noto
          sudo mv Noto /usr/local/share/fonts/
          sudo chmod 777 /usr/local/share/fonts/Noto/* -R
          sudo chmod 777 /usr/local/share/fonts/Noto
          sudo fc-cache -fv
      - name: Install Pandoc
        run: |
          sudo apt install pandoc
      - name: Run Guard
        run: "node .guard"
      - name: Save
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          user_name: "JacobLinCool"
          user_email: "jacoblincool@users.noreply.github.com"
          publish_branch: "homework"